AppCofidurBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: AppCofidurBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        ordre:
            type: integer
        nom:
            type: string
            length: 255
        idFormation:
            type: integer
    lifecycleCallbacks: {  }
