AppCofidurBundle\Entity\Formation:
    type: entity
    table: null
    repositoryClass: AppCofidurBundle\Repository\FormationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        typeFormation:
            type: string
            length: 255
        criticite:
            type: integer
        objectif:
            type: string
            length: 255
        moyensPedagogiques:
            type: string
            length: 255
        lieuMoyensMateriels:
            type: string
            length: 255
    lifecycleCallbacks: {  }