AppCofidurBundle\Entity\Formation:
    type: entity
    table: null
    repositoryClass: AppCofidurBundle\Repository\FormationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
    lifecycleCallbacks: {  }
