AppCofidurBundle\Entity\Operator:
    type: entity
    table: null
    repositoryClass: AppCofidurBundle\Repository\OperatorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
        lastName:
            type: string
            length: 255
            column: last_name
        dateOfBirth:
            type: date
            nullable: true
            column: date_of_birth
    lifecycleCallbacks: {  }
