AppCofidurBundle\Entity\Operator:
    type: entity
    table: null
    repositoryClass: AppCofidurBundle\Repository\OperatorRepository

    fields:
        dateOfBirth:
            type: date
            nullable: true
            column: date_of_birth
    lifecycleCallbacks: {  }
