AppCofidurBundle\Entity\Task:
    type: entity
    table: null
    repositoryClass: AppCofidurBundle\Repository\TaskRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idCategory:
            type: integer
        ordre:
            type: integer
        nom:
            type: string
            length: 255
    lifecycleCallbacks: {  }
