#pages de bases
AppCofidurBundle_homepage:
    path:  /
    defaults: { _controller: AppCofidurBundle:Page:index }


AppCofidurBundle_about:
    path:  /about
    defaults: { _controller: AppCofidurBundle:Page:about }


AppCofidurBundle_contact:
    path: /contact
    defaults: { _controller: AppCofidurBundle:Page:contact }


AppCofidurBundle_skillMatrix:
    path: /skillMatrix
    defaults: { _controller: AppCofidurBundle:skillMatrix:show }

# Pages d'authentifiation
AppCofidurBundle_login:
    path: /login
    defaults : { _controller: FOSUserBundle:Security:login}

#AppCofidurBundle_register:
#    path: /register
#    defaults : { _controller: FOSUserBundle:Security:register }

#AppCofidurBundle_changePassword:
#    path: /profile/change-password
#    defaults : { _controller: FOSUserBundle:Security:change-password}


# Page d'un opérateur
#CofidurBundle_add:
#    pattern: /operator/add
#    defaults: { _controller: AppCofidurBundle:Operator:add}

#page de formation
AppCofidurBundle_formation_add:
    path: /formation/add
    defaults: { _controller: AppCofidurBundle:Formation:add}

AppCofidurBundle_formation_edit:
    path:  /formation/edit/{idForm}
    defaults: { _controller: AppCofidurBundle:Formation:edit }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_delete:
    path:  /formation/delete/{idForm}
    defaults: { _controller: AppCofidurBundle:Formation:delete }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_show:
    path:  /formation/{idForm}
    defaults: { _controller: AppCofidurBundle:Formation:show }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_show_all:
    path:  /formations
    defaults: { _controller: AppCofidurBundle:Formation:showAll }

#page de categorie
AppCofidurBundle_category_add:
    path: /category/add/{idForm}
    defaults: { _controller: AppCofidurBundle:Category:add}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_category_edit:
    path: /category/edit/{idCat}
    defaults: { _controller: AppCofidurBundle:Category:edit}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_category_delete:
    path: /category/delete/{idCat}
    defaults: { _controller: AppCofidurBundle:Category:delete}
    requirements:
        methods: GET
        id: \d+

#page de taches
AppCofidurBundle_task_add:
    path: /task/add/{idCat}
    defaults: { _controller: AppCofidurBundle:Task:add}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_task_delete:
    path: /task/delete/{idTask}
    defaults: { _controller: AppCofidurBundle:Task:delete}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_task_edit:
    path: /task/edit/{idTask}
    defaults: { _controller: AppCofidurBundle:Task:edit}
    requirements:
        methods: GET
        id: \d+