#===== ROUTING =====#

### Pages générales ###
AppCofidurBundle_homepage:
    path:  /
    defaults: { _controller: AppCofidurBundle:Page:index }

AppCofidurBundle_about:
    path:  /about
    defaults: { _controller: AppCofidurBundle:Page:about }

AppCofidurBundle_contact:
    path: /contact
    defaults: { _controller: AppCofidurBundle:Page:contact }

AppCofidurBundle_admin:
    path: /admin
    defaults: { _controller: AppCofidurBundle:Page:admin }

### Matrice de compétences ###
AppCofidurBundle_skillMatrix:
    path: /skillMatrix
    defaults: { _controller: AppCofidurBundle:Page:skillMatrix }

### Pages d'authentifiation ###
AppCofidurBundle_login:
    path: /login
    defaults : { _controller: FOSUserBundle:Security:login}

AppCofidurBundle_logout:
    path: /logout
    defaults : { _controller: FOSUserBundle:Security:logout}

#AppCofidurBundle_register:
#    path: /register
#    defaults : { _controller: FOSUserBundle:Security:register }

#AppCofidurBundle_changePassword:
#    path: /profile/change-password
#    defaults : { _controller: FOSUserBundle:Security:change-password}


# Pages des opérateurs
AppCofidurBundle_operator_add:
    path: /operator/add
    defaults: { _controller: AppCofidurBundle:Operator:add}

AppCofidurBundle_operator_edit:
    path: /operator/edit/{idOp}
    defaults: { _controller: AppCofidurBundle:Operator:edit}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operator_delete:
    path: /operator/delete/{idOp}
    defaults: { _controller: AppCofidurBundle:Operator:delete}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operator_show:
    path: /operator/show/{idOp}
    defaults: { _controller: AppCofidurBundle:Operator:show}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operator_show_all:
    path: /operators
    defaults: { _controller: AppCofidurBundle:Operator:showAll}

### page de formation ###
AppCofidurBundle_formation_add:
    path: /formation/add
    defaults: { _controller: AppCofidurBundle:Formation:add}

AppCofidurBundle_formation_edit:
    path:  /formation/edit/{idForm}
    defaults: { _controller: AppCofidurBundle:Formation:edit }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_delete:
    path:  /formation/delete/{idForm}
    defaults: { _controller: AppCofidurBundle:Formation:delete }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_show:
    path:  /formation/{idForm}
    defaults: { _controller: AppCofidurBundle:Formation:show }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_show_all:
    path:  /formations
    defaults: { _controller: AppCofidurBundle:Formation:showAll }

### page de categorie ###
AppCofidurBundle_category_add:
    path: /category/add/{idForm}
    defaults: { _controller: AppCofidurBundle:Category:add}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_category_edit:
    path: /category/edit/{idCat}
    defaults: { _controller: AppCofidurBundle:Category:edit}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_category_delete:
    path: /category/delete/{idCat}
    defaults: { _controller: AppCofidurBundle:Category:delete}
    requirements:
        methods: GET
        id: \d+

### page de taches
AppCofidurBundle_task_add:
    path: /task/add/{idCat}
    defaults: { _controller: AppCofidurBundle:Task:add}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_task_edit:
    path: /task/edit/{idTask}
    defaults: { _controller: AppCofidurBundle:Task:edit}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_task_delete:
    path: /task/delete/{idTask}
    defaults: { _controller: AppCofidurBundle:Task:delete}
    requirements:
        methods: GET
        id: \d+

### Pages de formation d'opérateurs ###
AppCofidurBundle_operatorformation_add:
    path: /operatorformation/add/
    defaults: { _controller: AppCofidurBundle:OperatorFormation:add}

AppCofidurBundle_operatorformation_edit:
    path: /operatorformation/edit/{idOpForm}
    defaults: { _controller: AppCofidurBundle:OperatorFormation:edit}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operatorformation_delete:
    path: /operatorformation/delete/{idOpForm}
    defaults: { _controller: AppCofidurBundle:OperatorFormation:delete}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operatorformation_show:
    path:  /operatorformation/{idOpForm}
    defaults: { _controller: AppCofidurBundle:OperatorFormation:show }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operatorformation_show_all:
    path:  /operatorsformations/
    defaults: { _controller: AppCofidurBundle:OperatorFormation:showAll }

#pages de operatorcategory
AppCofidurBundle_operatorcategory_add:
    path: /operatorcategory/add/{idOpForm}/{idCategory}
    defaults: { _controller: AppCofidurBundle:OperatorCategory:add}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operatorcategory_edit:
    path: /operatorcategory/edit/{idOpForm}/{idCategory}
    defaults: { _controller: AppCofidurBundle:OperatorCategory:edit}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operatorcategory_delete:
    path: /operatorcategory/delete/{idOpForm}/{idCategory}
    defaults: { _controller: AppCofidurBundle:OperatorCategory:delete}
    requirements:
        methods: GET
        id: \d+

#page de operatortasks
AppCofidurBundle_operatortask_add:
    path: /operatortask/add/{idOpForm}/{idCategory}/{idTask}
    defaults: { _controller: AppCofidurBundle:OperatorTask:add}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_operatortask_delete:
    path: /operatortask/delete/{idOpForm}/{idCategory}/{idTask}
    defaults: { _controller: AppCofidurBundle:OperatorTask:delete}
    requirements:
        methods: GET
        id: \d+
