#pages de bases
AppCofidurBundle_homepage:
    path:  /
    defaults: { _controller: AppCofidurBundle:Page:index }


AppCofidurBundle_about:
    path:  /about
    defaults: { _controller: AppCofidurBundle:Page:about }


AppCofidurBundle_contact:
    path: /contact
    defaults: { _controller: AppCofidurBundle:Page:contact }


AppCofidurBundle_skillMatrix:
    path: /skillMatrix
    defaults: { _controller: AppCofidurBundle:skillMatrix:show }


# Page de connexion
#
#AppCofidurBundle_login:
#    path: /login
#    defaults: { _controller: AppCofidurBundle:login }
#}

# Page d'un opérateur
#CofidurBundle_add:
#    pattern: /operator/add
#    defaults: { _controller: AppCofidurBundle:Operator:add}

#page de formation
AppCofidurBundle_formation_add:
    path: /formation/add
    defaults: { _controller: AppCofidurBundle:Formation:add}

AppCofidurBundle_formation_edit:
    path:  /formation/edit/{id}
    defaults: { _controller: AppCofidurBundle:Formation:edit }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_delete:
    path:  /formation/delete/{id}
    defaults: { _controller: AppCofidurBundle:Formation:delete }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_show:
    path:  /formation/{id}
    defaults: { _controller: AppCofidurBundle:Formation:show }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_show_all:
    path:  /formation
    defaults: { _controller: AppCofidurBundle:Formation:showAll }

#page de categorie
AppCofidurBundle_categorie_add:
    path: /categorie/add/{idForm}
    defaults: { _controller: AppCofidurBundle:Categorie:add}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_categorie_edit:
    path: /categorie/edit/{idCat}
    defaults: { _controller: AppCofidurBundle:Categorie:edit}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_categorie_delete:
    path: /categorie/delete/{idCat}
    defaults: { _controller: AppCofidurBundle:Categorie:delete}
    requirements:
        methods: GET
        id: \d+

#page de taches
AppCofidurBundle_tache_add:
    path: /tache/add/{idCat}
    defaults: { _controller: AppCofidurBundle:Tache:add}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_tache_delete:
    path: /tache/delete/{idTache}
    defaults: { _controller: AppCofidurBundle:Tache:delete}
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_tache_edit:
    path: /tache/edit/{idTache}
    defaults: { _controller: AppCofidurBundle:Tache:edit}
    requirements:
        methods: GET
        id: \d+