#pages de bases
AppCofidurBundle_homepage:
    path:  /
    defaults: { _controller: AppCofidurBundle:Page:index }


AppCofidurBundle_about:
    path:  /about
    defaults: { _controller: AppCofidurBundle:Page:about }


AppCofidurBundle_contact:
    path: /contact
    defaults: { _controller: AppCofidurBundle:Page:contact }


#page d'operator
#CofidurBundle_add:
#    pattern: /operator/add
#    defaults: { _controller: AppCofidurBundle:Operator:add}


#page de formation
AppCofidurBundle_formation_show:
    path:  /formation/show/{id}
    defaults: { _controller: AppCofidurBundle:Formation:show }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_show_all:
    path:  /formation/show/
    defaults: { _controller: AppCofidurBundle:Formation:showAll }