#pages de bases
AppCofidurBundle_homepage:
    path:  /
    defaults: { _controller: AppCofidurBundle:Page:index }


AppCofidurBundle_about:
    path:  /about
    defaults: { _controller: AppCofidurBundle:Page:about }


AppCofidurBundle_contact:
    path: /contact
    defaults: { _controller: AppCofidurBundle:Page:contact }


#page d'operator
#CofidurBundle_add:
#    pattern: /operator/add
#    defaults: { _controller: AppCofidurBundle:Operator:add}


#page de formation
AppCofidurBundle_create:
    path: /formations/add
    defaults: { _controller: AppCofidurBundle:Formation:add}

AppCofidurBundle_formation_edit:
    path:  /formations/edit/{id}
    defaults: { _controller: AppCofidurBundle:Formation:edit }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_show:
    path:  /formations/{id}
    defaults: { _controller: AppCofidurBundle:Formation:show }
    requirements:
        methods: GET
        id: \d+

AppCofidurBundle_formation_show_all:
    path:  /formations
    defaults: { _controller: AppCofidurBundle:Formation:showAll }