AppCofidurBundle_homepage:
    pattern:  /
    defaults: { _controller: AppCofidurBundle:Page:index }


AppCofidurBundle_about:
    pattern:  /about
    defaults: { _controller: AppCofidurBundle:Page:about }


AppCofidurBundle_contact:
    pattern: /contact
    defaults: { _controller: AppCofidurBundle:Page:contact }

AppCofidurBundle_add:
    pattern: /operator/add
    defaults: { _controller: AppCofidurBundle:Operator:add}